### PR TITLE
Update testnet-platform.md

### PR DESCRIPTION
**Pull request by syadluq**
RAW "How To" Change needed, based on my experience tried the Testnetwork

### CODE REVIEW

**Comment by ngkong** [comment]
score removed because it changed only the text. as announced on the previous period that text changed PR will not subject to reward calculation. thank you for your participation

**Comment by syadluq** [comment]
Sorry @ngkong but i write all of them (not copy paste) + add picture tutorial on #55 so its not just text

**Comment by syadluq** [comment]
And this is the "Initial" docs, was "Documentation Coming Soon" on Main Branch

**Comment by syadluq** [comment]
Pull Requests eligible for rewards must have the following criteria:

1. In accordance with the roadmap and objectives of Tadpole Finance.
2. Describe in detail the changes, improvements or improvements that have been made.
3. Include test results (if any).
4. Applies to all repositories on Github @ Tadpole-finance
5. PR is not just fixing typos / grammar.

Point 1 this is the roadmap and objectives of Tadpole Finance, 2nd Point i Described all How to Test in Testnet, 3rd Point i Include the Test Result both on this PR and #55 , 5th Point this is not a Typos/Grammar Fix

**Pull request merged**
